- name: Copy private key to remote system
  ansible.builtin.copy:
    src: "{{ ssh_private_key_path }}"
    dest: /home/{{ user_name }}/.ssh/{{ ssh_private_key_name }}
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0600'

- name: Add private key to SSH agent
  ansible.builtin.shell: |
    eval $(ssh-agent)
    ssh-add /home/{{ user_name }}/.ssh/{{ ssh_private_key_name }}
  args:
    executable: /bin/bash

- name: Add Git server's public key to known_hosts
  ansible.builtin.known_hosts:
    name: github.com
    key: "{{ lookup('url', 'https://github.com/ssh/keys', wantlist=True) }}"
    state: present