---
- name: Create the folder
  ansible.builtin.file:
    path: "/home/{{ user_name }}"
    state: directory
    mode: '0755'

- name: Create user
  ansible.builtin.user:
    name: "{{ user_name }}"
    state: present
    create_home: yes
    password_lock: yes

- name: Set correct ownership and permissions for user directory
  ansible.builtin.file:
    path: "/home/{{ user_name }}"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0700"

- name: Ensure PubkeyAuthentication is set to yes in sshd_config
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PubkeyAuthentication'
    line: "PubkeyAuthentication yes"

- name: Set authorized key taken from file
  ansible.posix.authorized_key:
    user: "{{ user_name }}"
    state: present
    key: "{{ lookup('file', ssh_key_path) }}"

- name: Restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted
    daemon_reload: yes
